services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    command: bash   # 👈 evita di eseguire ./server all'avvio
    networks:
      - trisnet
    stdin_open: true
    tty: true

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - server
    volumes:
      - ./client:/app
    command: bash   # 👈 evita crash se ./client non ancora compilato
    networks:
      - trisnet
    stdin_open: true
    tty: true
    
networks:
  trisnet:
    driver: bridge